name: Develop Version Branch Automation

on:
  create:

permissions:
  contents: write
  pull-requests: write

jobs:
  handle-develop-version-branch:
    name: Handle develop-x.y.z branch creation
    runs-on: ubuntu-24.04
    if: startsWith(github.ref_name, 'develop-') && github.ref_type == 'branch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          VERSION=$(echo "$BRANCH_NAME" | sed 's/develop-//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      - name: Update pubspec.yaml version
        run: |
          VERSION="${{ steps.extract_version.outputs.version }}"
          PUBSPEC_PATH="pubspec.yaml"
          
          # Update version in pubspec.yaml (preserve existing version code)
          if grep -q "^version:" "$PUBSPEC_PATH"; then
            # Get current version code
            CURRENT_VERSION_CODE=$(grep "^version:" "$PUBSPEC_PATH" | sed -E 's/version:\s*[^+]+\+//' || echo "1")
            # Update with new version
            sed -i "s/^version:.*/version: ${VERSION}+${CURRENT_VERSION_CODE}/" "$PUBSPEC_PATH"
          else
            echo "Error: version field not found in $PUBSPEC_PATH"
            exit 1
          fi
          
          echo "Updated version to ${VERSION}+${CURRENT_VERSION_CODE}"
      - name: Commit version update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add pubspec.yaml
          git commit -m "feat: update version to ${{ steps.extract_version.outputs.version }} for parallel development
          
          Automatically updated version in pubspec.yaml for develop-${{ steps.extract_version.outputs.version }} branch.
          
          Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          
          git push origin ${{ steps.extract_version.outputs.branch_name }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_version.outputs.branch_name }}
          base: develop
          title: "feat: parallel development branch for v${{ steps.extract_version.outputs.version }}"
          body: |
            ## Overview
            
            Automated creation of parallel development branch for v${{ steps.extract_version.outputs.version }}
            
            - Automatically updated pubspec.yaml version to `${{ steps.extract_version.outputs.version }}`
            - This PR prepares the `${{ steps.extract_version.outputs.branch_name }}` branch for parallel development
            
            ## Important Notice
            
            ⚠️ **Branch Protection Rules Update Required** ⚠️
            
            Before starting parallel development on this branch, please update the following settings:
            
            1. **Branch Rulesets**: Apply rulesets to the `develop-${{ steps.extract_version.outputs.version }}` pattern as needed
            
            ## Review Points
            
            - Verify that pubspec.yaml version update is correct
            - Confirm branch protection settings are configured
            
            ## Notes
            
            This PR was automatically generated by GitHub Actions.
            It runs as part of the branch automation when develop-x.y.z branches are created.
          draft: false
